version: '3'
services:
  servdb:
    restart: always
    image: postgres:latest
    container_name: pgcontainer
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db1
    volumes:
      - /tmp/data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - dockernet

  golang:
    restart: always
    container_name: gocontainer
    build:
      context: .
      args:
        - A_DB_USER=postgres
        - A_DB_PASS=postgres
        - A_DB_BASE=books
        - A_DB_HOST=servdb
        - A_DB_PORT=5432
        - A_HTTP_PORT=8080
        - A_HTTP_HOST=0.0.0.0
        
    ports:
      - "5432"
      - "8080:8080"  
    networks:
      - dockernet

networks:
  dockernet:
    driver: bridge
          



